name: Nautix CI

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                compiler: [gcc, clang]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    build-essential \
                    cmake \
                    ninja-build \
                    clang \
                    gcc \
                    g++ \
                    pkg-config \
                    libgtkmm-4.0-dev \
                    clang-format \
                    clang-tidy

            - name: Configure CMake
              run: |
                  cmake -S . -B build \
                    -G Ninja \
                    -DCMAKE_BUILD_TYPE=Debug \
                    -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++

            - name: Build
              run: cmake --build build --parallel

            - name: Run tests
              run: ctest --output-on-failure --test-dir build/tests

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install clang-format and clang-tidy
              run: |
                  sudo apt-get update
                  sudo apt-get install -y clang-format clang-tidy

            - name: Run clang-format check
              run: |
                  clang-format --dry-run --Werror $(find src tests -name "*.cpp" -o -name "*.h")

            - name: Run clang-tidy check
              run: |
                  clang-tidy $(find src tests -name "*.cpp") -- -I./src
